package com.sullivan.treegenerator;

import com.sullivan.treegenerator.model.DirectoryNode;
import java.io.File;
import java.io.IOException;
import java.util.Scanner;

/**
 * <h1>TreeDirectory App</h1>
 * @author Shawn Sullivan
 * CEN 4025C - 14148 <br>
 * August 30, 2025 <br>
 * This application stores the tree file structure of a given file path for the user and prints that tree directory
 * structure to the console for the user to review.
 */

public class TreeDirectoryApp {

    /**
     * Returns a DirectoryNode object generated by traversing all child directories and files given root file through
     * recursive calls of the method.
     * @param directory File object generated from file path provided by the user through the CLI GUI
     * @return DirectoryNode object including a List attribute containing nested DirectoryNode objects
     * @throws IOException in the case that the path provided by the user to is invalid as it will not be caught when
     * the File object is created
     */
    public static DirectoryNode treeGenerator(File directory) throws IOException {

        DirectoryNode node = new DirectoryNode(directory.getName(), directory.isDirectory());

        if (directory.isDirectory()) {
            File[] files = directory.listFiles();
            if (files != null) {
                // Recursive method call to traverse directory tree and store relevant information for printing
                // as DirectoryNode objects. Child directories/files are stored as DirectoryNodes nested in the parent
                // DirectoryNode in the List children attribute
                for (File file : files) {
                    DirectoryNode child = treeGenerator(file);
                    node.getChildren().add(child);
                    node.setFileCount(node.getFileCount() + child.getFileCount());
                    node.setTotalSize(node.getTotalSize() + child.getTotalSize());
                    }
            }
        }
        else {
            // Data storage for individual files to display size in tree print out
            node.setFileCount(1);
            node.setTotalSize(directory.length());
        }
        return node;
    }

    /**
     * Returns a version of the DirectoryNode.totalSize formatted to utilize standard data unites KB, MB, etc.
     * for readability on tree print out (boilerplate code)
     * @param bytes long value stored as an attribute of each DirectoryNode object
     * @return String formatted using standard data units
     */
    private static String byteSize(long bytes) {
        if (bytes < 1024) {
            return bytes + " B";
        }
        int exp = (int) (Math.log(bytes) / Math.log(1024));
        String unit = "KMGTPE".charAt(exp - 1) + "B";
        return String.format("%.1f %s", bytes / Math.pow(1024, exp), unit);
    }

    /**
     * Prints a visual representation of a tree directory data structure to the console based on the root DirectoryNode
     * provided
     * @param node DirectoryNode object set as the root note for the tree directory structure
     * @param depth helper parameter used to enable visually ques for nesting of directories and folders within the tree
     */
    public static void printTree(DirectoryNode node, int depth) {
        System.out.println(
            "  ".repeat(depth) +
            (node.isDirectory() ?
                ">"+ node.getFileName() + " (" + node.getFileCount() + " files " + byteSize(node.getTotalSize()) + ")" :
                "|--" + node.getFileName() + " " + byteSize(node.getTotalSize())
            )
        );
        for (DirectoryNode child : node.getChildren()) {
            printTree(child, depth + 1);
        }
    }

    public static void main(String[] args) {
        boolean run = true;
        Scanner sc = new Scanner(System.in);

        while (run) {
            System.out.println("\nWelcome to Directory Visualizer");
            System.out.println("1. Create Directory Tree Visualizer");
            System.out.println("2. Exit Application");
            System.out.println("Select from the options above: ");
            String choice = sc.nextLine();

            switch (choice) {
                case "1":
                    System.out.println("Enter the path of the root file for your directory: ");
                    String rootPath = sc.nextLine();
                    File rootFile = new File(rootPath);
                    try {
                        if (!rootFile.exists() || !rootFile.isDirectory()) {
                            System.out.println("Directory does not exist or is not a directory.");
                            break;
                        }
                        DirectoryNode root = treeGenerator(rootFile);
                        printTree(root, 0);
                    }
                    catch (IOException e) {
                        System.out.println("Error: " + e.getMessage());
                    }
                    break;
                case "2":
                    run = false;
                    System.out.println("Thanks for using the Directory Visualizer");
                    break;
                default:
                    System.out.println("Invalid choice. Please try again.");
                    break;
            }
        }
    }
}
